### ISSUE TITLE
Invalid JSON file format raises exception

### ISSUE THREAD

**Issue by hkraal** [hkraal/ssht#8]
```python
Traceback (most recent call last):
  File "/usr/local/bin/ssht", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/ssht/ssht.py", line 75, in main
    jsonparser = JsonParser(os.path.join(home_dir, '.ssht'))
  File "/usr/local/lib/python2.7/dist-packages/ssht/plugins.py", line 64, in __init__
    self._load_data()
  File "/usr/local/lib/python2.7/dist-packages/ssht/plugins.py", line 79, in _load_data
    except json.decoder.JSONDecodeError as ex:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

**Comment by hkraal** [comment]
Fixed in dcc9a54715c577876dabb1cc67f878e44b485eae
